# Generated by Django 5.1.2 on 2024-10-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('setor', models.CharField(max_length=150, verbose_name='Setor')),
                ('funcao', models.CharField(max_length=250, verbose_name='Função')),
            ],
        ),
    ]
