# Generated by Django 5.1.2 on 2024-10-28 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_maquinas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Maquinas',
            new_name='Maquina',
        ),
    ]
